### ISSUE TITLE
URL change breaks CSS / Images and Navigation

### ISSUE THREAD

**Issue by WillieAhlers1** [microsoft/dstoolkit-web#98]
Need to figure out what has to change when the URL is changed.

It seems the config yml file needs to be updated, however the new URL is of the format 'microsoft.github.io**/dstoolkit-web**' the old was of the format 'crispyparakeet.github.io' It seems the 'base url' property in the YML file has something to do with this. I wonder if the 'permalinks' have to be updated in each markdown page?

**Comment by WillieAhlers1** [comment]
@mtran-affirma could you take a look at why this is happening please, it seems that there is some place we are not updating the URL and BaseURL correctly?

**Comment by mshelldev** [comment]
hi @WillieAhlers1 and @strobaek , 

under Settings > Pages, you should see the setting to configure the custom domain along with a link to documentation for how to configure:

![image](https://user-images.githubusercontent.com/101883224/177408771-cb3b5d1e-a41a-4fa1-9a29-e627d07762a8.png)

**Comment by strobaek** [comment]
> hi @WillieAhlers1 and @strobaek , 
> 
> under Settings > Pages, you should see the setting to configure the custom domain along with a link to documentation for how to configure:
> 
> ![image](https://user-images.githubusercontent.com/101883224/177408771-cb3b5d1e-a41a-4fa1-9a29-e627d07762a8.png)
> 

Hi,
It is not a question of setting a custom domain. The url changed when repo was set to public. From [something]/ to [something]/dstoolkit-web/.
This seems to be the problem.
As Willie write he has changed the url in the _config.yml file, but to no avail.

**Comment by strobaek** [comment]
Hi @mtran-affirma ,

I don't believe it has anything to do with custom domains.

The site url changes to also contain a 'subpage' (I believe). 

I think this is what is causing the problems.

/cc @WillieAhlers1

**Comment by WillieAhlers1** [comment]
@mtran-affirma - click on this url - https://microsoft.github.io/dstoolkit-web/ to see what the issue is :) 
As @strobaek  indicated, it is not about changing the custom URL, but more about CSS / Navigations issues once the URL is changed.

**Comment by mshelldev** [comment]
ah okay I see, thanks for clarifying @WillieAhlers1 and @strobaek !

Do you see the same behavior when running the site and testing locally?

If you don't, then yes, it's possible the image links being broken on the public site may have to do with the _config.yml file then. I do not see much documentation online for this so I would recommend using a different branch to try and fix the bug and test the changes locally before merging back into the main/master branch, gh-pages.

**Comment by strobaek** [comment]
@mtran-affirma ,

Thx. The challenge with testing locally is, that it does not have the subpage, hence it looks fine.

**Comment by mshelldev** [comment]
Okay thanks for confirming, @strobaek ! So okay, that makes sense why you've been updating directly on the gh-pages branch.

Doing some more research, I found someone else that faced a similar issue: https://github.community/t/broken-images/10485

The marked answer mentions a fix of removing "../" from image src paths:
![image](https://user-images.githubusercontent.com/101883224/177577013-cd420080-2f4c-427e-b2b9-5040bb983a38.png)

When I look at the website, you can see the url of the image it's trying to pull:
![image](https://user-images.githubusercontent.com/101883224/177576921-3d502667-8674-416c-822c-634422253da8.png)

To test the fix mentioned in the forum, I tried it on one image on the home page, and it worked!
Commit: https://github.com/microsoft/dstoolkit-web/commit/a9d9da4511d2cf00fa2e969ce6616ce5721d5857
![image](https://user-images.githubusercontent.com/101883224/177577713-53940ec4-f816-4a37-8e66-5d175e742d6f.png)

So then, the fix for any images that are broken is to apply the same fix as was applied in commit https://github.com/microsoft/dstoolkit-web/commit/a9d9da4511d2cf00fa2e969ce6616ce5721d5857

cc: @WillieAhlers1

**Comment by mshelldev** [comment]
hi @strobaek @WillieAhlers1  , here's a blog you may find useful: https://mademistakes.com/mastering-jekyll/site-url-baseurl/

I noticed it isn't just links to images, but also other internal links such as links to other pages within the GitHub pages site

Also FYI, whenever a commit is made to the main branch, gh-pages, the deployment to the site will trigger of which you can view the status of here to confirm that you're seeing the latest committed version: https://github.com/microsoft/dstoolkit-web/actions

**Comment by mshelldev** [comment]
okay hi again @strobaek and @WillieAhlers1 , I discovered the fix for fixing internal links - one needs to add the site.baseurl variable to the front of a url as per https://mademistakes.com/mastering-jekyll/site-url-baseurl/:

You can see I fixed the Home page link on the navigation bar with this commit:
https://github.com/microsoft/dstoolkit-web/commit/d3d44c66020b8b38c04b7f69129c3cddc6b54dca

before, going to "Home" would take you to https://microsoft.github.io/ which redirects to https://opensource.microsoft.com/

now it correctly takes you to the Home page

**Comment by strobaek** [comment]
Thank you @mtran-affirma.
I will run through the site 'properly' and correct the images and links.

**Comment by mshelldev** [comment]
hi @strobaek , i took a quick look at the site and tested some of the links! FYI that the link for the logo image also needs to be updated:
![image](https://user-images.githubusercontent.com/101883224/177795701-045ceae2-5bfb-4d87-a4d3-196f83a95123.png)

cc: @WillieAhlers1
